server:
  error:
    include-stacktrace: NEVER
spring:
  datasource:
    url: jdbc:h2:mem:mem;mode=MySQL;database_to_lower=true
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: true
    property-naming-strategy: SNAKE_CASE