SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE `permission`(
	`id` BIGINT NOT NULL AUTO_INCREMENT ,
	`name` VARCHAR(60) NOT NULL,
	`created_at` DATETIME(0) NOT NULL,
	`modified_at` DATETIME(0) NOT NULL,
	`enabled` BIT(1) NOT NULL,
	CONSTRAINT `pkPermission` PRIMARY KEY (`id`)
);

ALTER TABLE `permission` ADD CONSTRAINT `ukPermission_name` UNIQUE (`name`);

INSERT INTO `permission` (name, created_at, modified_at, enabled) VALUES
    ('PERMISSION_READ', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, TRUE),
    ('USER_READ', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, TRUE);


SET FOREIGN_KEY_CHECKS=1;
